import { test, expect, chromium } from '@playwright/test';

// Helper function to generate focalboard-compatible random IDs
function generateGuid() {
  const chars = 'abcdefghijklmnopqrstuvwxyz0123456789';
  let result = '';
  for (let i = 0; i < 26; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
}

// Helper function to register a user via the API
async function registerUser(request: any, username: string, email: string, password: string, signupToken: string = '') {
  const response = await request.post('/api/v2/register', {
    data: {
      username,
      email,
      password,
      token: signupToken,
    },
    headers: {
      'X-Requested-With': 'XMLHttpRequest',
    }
  });
  return response;
}

// Helper to log in a user and return the token and user ID
async function loginUser(request: any, username: string, password: string) {
  const response = await request.post('/api/v2/login', {
    data: {
      type: 'normal',
      username,
      password,
    },
    headers: {
      'X-Requested-With': 'XMLHttpRequest',
    }
  });
  expect(response.status()).toBe(200);
  const data = await response.json();
  
  // Get Me to retrieve user ID
  const meResponse = await request.get('/api/v2/users/me', {
    headers: {
      'Authorization': `Bearer ${data.token}`,
      'X-Requested-With': 'XMLHttpRequest',
    }
  });
  expect(meResponse.status()).toBe(200);
  const meData = await meResponse.json();
  
  return { token: data.token, userId: meData.id };
}

// Helper to inject local storage for login bypass in Playwright context
async function loginBypass(page: any, token: string) {
  // First go to /login to establish the origin context
  await page.goto('/login');
  // Inject tokens into localStorage
  await page.evaluate((sessionToken: string) => {
    window.localStorage.setItem('focalboardSessionId', sessionToken);
    window.localStorage.setItem('welcomePageViewed', 'true');
    window.localStorage.setItem('language', 'en');
  }, token);
}

test.describe('Focalboard Concurrency and Non-Functional Tests', () => {
  let user1Token: string;
  let user1Id: string;
  let user2Token: string;
  let user2Id: string;
  let boardId: string;
  let cardId: string;
  let signupToken: string = '';

  const password = 'Password123!';
  const username1 = 'concurrency_test_user_1';
  const username2 = 'concurrency_test_user_2';
  const email1 = 'concurrency_test_user_1@test.com';
  const email2 = 'concurrency_test_user_2@test.com';

  test.beforeAll(async ({ request }) => {
    console.log('--- Setting up test users via API ---');
    
    // Register U1 (Admin/First user) if not already registered
    const registerU1Resp = await registerUser(request, username1, email1, password);
    if (registerU1Resp.status() === 200) {
      console.log(`Registered new User 1: ${username1}`);
    } else {
      console.log(`User 1 registration returned status ${registerU1Resp.status()}, attempting login fallback...`);
    }

    const u1 = await loginUser(request, username1, password);
    user1Token = u1.token;
    user1Id = u1.userId;
    console.log(`User 1 Logged in: ${username1} (ID: ${user1Id})`);

    // Get the Team Signup Token using User 1 token
    const teamResponse = await request.get('/api/v2/teams/0', {
      headers: {
        'Authorization': `Bearer ${user1Token}`,
        'X-Requested-With': 'XMLHttpRequest',
      }
    });
    expect(teamResponse.status()).toBe(200);
    const teamData = await teamResponse.json();
    signupToken = teamData.signupToken;
    console.log(`Retrieved signup token for default team: ${signupToken}`);

    // Register U2 if not already registered
    const registerU2Resp = await registerUser(request, username2, email2, password, signupToken);
    if (registerU2Resp.status() === 200) {
      console.log(`Registered new User 2: ${username2}`);
    } else {
      console.log(`User 2 registration returned status ${registerU2Resp.status()}, attempting login fallback...`);
    }

    const u2 = await loginUser(request, username2, password);
    user2Token = u2.token;
    user2Id = u2.userId;
    console.log(`User 2 Logged in: ${username2} (ID: ${user2Id})`);

    // Generate client-side temp IDs (will be mapped and regenerated by server)
    const tempBoardId = generateGuid();
    const tempCardId = generateGuid();
    const tempViewId = generateGuid();
    const tempStatusPropId = generateGuid();

    console.log(`--- Creating board, view, and card via API ---`);

    const boardPayload = {
      id: tempBoardId,
      teamId: '0',
      channelId: '',
      title: 'Concurrency Board',
      type: 'P',
      minimumRole: '',
      description: '',
      icon: '',
      showDescription: false,
      isTemplate: false,
      templateVersion: 0,
      properties: {},
      cardProperties: [
        {
          id: tempStatusPropId,
          name: 'Status',
          type: 'select',
          options: [
            { id: 'opt-todo', value: 'To Do', color: 'propColorDefault' },
            { id: 'opt-inprogress', value: 'In Progress', color: 'propColorDefault' },
            { id: 'opt-done', value: 'Done', color: 'propColorDefault' }
          ]
        }
      ],
      createAt: Date.now(),
      updateAt: Date.now(),
      deleteAt: 0
    };

    const blocksPayload = [
      {
        id: tempViewId,
        parentId: tempBoardId,
        boardId: tempBoardId,
        type: 'view',
        title: 'Board view',
        fields: {
          viewType: 'board',
          groupById: tempStatusPropId,
          visiblePropertyIds: [tempStatusPropId],
          visibleOptionIds: ['opt-todo', 'opt-inprogress', 'opt-done'],
          hiddenOptionIds: []
        },
        createAt: Date.now(),
        updateAt: Date.now(),
        deleteAt: 0
      },
      {
        id: tempCardId,
        parentId: tempBoardId,
        boardId: tempBoardId,
        type: 'card',
        title: 'Initial Concurrency Card Title',
        fields: {
          properties: {
            [tempStatusPropId]: 'opt-todo'
          }
        },
        createAt: Date.now(),
        updateAt: Date.now(),
        deleteAt: 0
      }
    ];

    const createResponse = await request.post('/api/v2/boards-and-blocks', {
      data: {
        boards: [boardPayload],
        blocks: blocksPayload
      },
      headers: {
        'Authorization': `Bearer ${user1Token}`,
        'X-Requested-With': 'XMLHttpRequest'
      }
    });
    expect(createResponse.status()).toBe(200);
    
    // Retrieve server-generated final IDs from response
    const createData = await createResponse.json();
    boardId = createData.boards[0].id;
    const cardBlock = createData.blocks.find((b: any) => b.type === 'card');
    cardId = cardBlock.id;
    console.log(`Created board, view, and card successfully via API.`);
    console.log(`Server-generated Board ID: ${boardId}, Card ID: ${cardId}`);

    // Share Board with User 2 via API
    const memberResponse = await request.post(`/api/v2/boards/${boardId}/members`, {
      data: {
        boardId,
        userId: user2Id,
        schemeEditor: true,
      },
      headers: {
        'Authorization': `Bearer ${user1Token}`,
        'X-Requested-With': 'XMLHttpRequest',
      }
    });
    expect(memberResponse.status()).toBe(200);
    console.log(`Added User 2 to board ${boardId}`);
    console.log('Setup finished successfully!');
  });

  test('CON-01: Conflicto de escritura (Race Condition) - Last Write Wins verification', async ({ baseURL }) => {
    console.log('\n--- Running CON-01: Conflicto de escritura (Race Condition) ---');
    const browser = await chromium.launch();
    
    // Create browser context for User 1
    const context1 = await browser.newContext({ baseURL });
    const page1 = await context1.newPage();
    await loginBypass(page1, user1Token);

    // Create browser context for User 2
    const context2 = await browser.newContext({ baseURL });
    const page2 = await context2.newPage();
    await loginBypass(page2, user2Token);

    // Navigate both users to the board
    console.log(`Navigating both users to the board: /${boardId}`);
    await page1.goto(`/${boardId}`);
    await page2.goto(`/${boardId}`);

    await expect(page1.locator('.BoardComponent')).toBeVisible({ timeout: 15000 });
    await expect(page2.locator('.BoardComponent')).toBeVisible({ timeout: 15000 });

    // Open card modal on both pages
    console.log('Opening card detail modal for both users...');
    await page1.locator('.KanbanCard').first().click();
    await page2.locator('.KanbanCard').first().click();

    // Ensure the card detail modal is visible (using .first() to avoid strict mode violations)
    await expect(page1.locator('.CardDetail').first()).toBeVisible();
    await expect(page2.locator('.CardDetail').first()).toBeVisible();

    const editInput1 = page1.locator('.CardDetail .EditableArea.title').first();
    const editInput2 = page2.locator('.CardDetail .EditableArea.title').first();

    // Both users edit the title
    console.log('Typing different titles on both pages...');
    await editInput1.click();
    await editInput1.clear();
    await editInput1.fill('Title Edit by User 1');

    await editInput2.click();
    await editInput2.clear();
    await editInput2.fill('Title Edit by User 2');

    // Prepare to capture PATCH requests
    const patchPromises = [
      page1.waitForResponse(response => 
        response.url().includes(`/api/v2/boards/${boardId}/blocks/${cardId}`) && 
        response.request().method() === 'PATCH'
      ),
      page2.waitForResponse(response => 
        response.url().includes(`/api/v2/boards/${boardId}/blocks/${cardId}`) && 
        response.request().method() === 'PATCH'
      )
    ];

    // Trigger save (blur) concurrently
    console.log('Saving titles concurrently...');
    await Promise.all([
      editInput1.blur(),
      editInput2.blur()
    ]);

    // Wait for patch responses
    const responses = await Promise.all(patchPromises);
    console.log(`User 1 Patch Response status: ${responses[0].status()}`);
    console.log(`User 2 Patch Response status: ${responses[1].status()}`);

    // Verify both operations completed with 200
    expect(responses[0].status()).toBe(200);
    expect(responses[1].status()).toBe(200);

    // Give time for WebSocket updates to propagate and db to persist
    await page1.waitForTimeout(1000);

    // Re-fetch card title from database via API
    const finalCardResponse = await page1.request.get(`/api/v2/boards/${boardId}/blocks?block_id=${cardId}`, {
      headers: {
        'Authorization': `Bearer ${user1Token}`,
        'X-Requested-With': 'XMLHttpRequest',
      }
    });
    const finalCardData = await finalCardResponse.json();
    const finalTitle = finalCardData[0].title;
    console.log(`Final persisted Card Title: "${finalTitle}"`);

    // Verify it is one of the two edits
    expect(['Title Edit by User 1', 'Title Edit by User 2']).toContain(finalTitle);

    await context1.close();
    await context2.close();
    await browser.close();
  });

  test('CON-02: Conflicto de Schema y Datos - Card Move vs Column Delete', async ({ request }) => {
    console.log('\n--- Running CON-02: Card Move vs Column Delete ---');
    
    // Fetch the created board metadata using API
    const boardResponse = await request.get(`/api/v2/boards/${boardId}`, {
      headers: {
        'Authorization': `Bearer ${user1Token}`,
        'X-Requested-With': 'XMLHttpRequest',
      }
    });
    expect(boardResponse.status()).toBe(200);
    const boardData = await boardResponse.json();
    
    // Check if cardProperties exist and contain status select options
    const cardProperties = boardData.cardProperties || [];
    const statusProp = cardProperties.find((p: any) => p.name === 'Status' && p.type === 'select');
    if (!statusProp) {
      console.log('No Status property found, skipping CON-02.');
      return;
    }
    
    const options = statusProp.options || [];
    if (options.length < 2) {
      console.log('Not enough options/columns on board to perform test.');
      return;
    }
    
    const optionToMoveTo = options[options.length - 1]; // Let's use the last column ("Done")
    const optionToMoveToId = optionToMoveTo.id;
    console.log(`Target column to move to and delete: "${optionToMoveTo.value}" (ID: ${optionToMoveToId})`);

    // Prepare User 1 move request payload (Patch Card block)
    const cardPatchPayload = {
      updatedFields: {
        properties: {
          [statusProp.id]: optionToMoveToId
        }
      }
    };

    // Prepare User 2 schema update payload (Patch Board block options)
    // We remove the target option from the options list
    const updatedOptions = options.filter((opt: any) => opt.id !== optionToMoveToId);
    const updatedCardProperties = cardProperties.map((p: any) => {
      if (p.id === statusProp.id) {
        return { ...p, options: updatedOptions };
      }
      return p;
    });

    const boardPatchPayload = {
      updatedCardProperties: updatedCardProperties
    };

    console.log('Sending concurrent Card Move (U1) and Column Delete (U2) requests...');
    const responses = await Promise.all([
      // U1 moves card
      request.patch(`/api/v2/boards/${boardId}/blocks/${cardId}`, {
        headers: {
          'Authorization': `Bearer ${user1Token}`,
          'X-Requested-With': 'XMLHttpRequest',
          'Content-Type': 'application/json'
        },
        data: cardPatchPayload
      }),
      // U2 deletes option/column from board
      request.patch(`/api/v2/boards/${boardId}`, {
        headers: {
          'Authorization': `Bearer ${user2Token}`,
          'X-Requested-With': 'XMLHttpRequest',
          'Content-Type': 'application/json'
        },
        data: boardPatchPayload
      })
    ]);

    console.log(`Card Move Response Status: ${responses[0].status()}`);
    console.log(`Column Delete Response Status: ${responses[1].status()}`);

    // Verify both operations are processed gracefully by the server
    expect(responses[0].status()).toBe(200);
    expect(responses[1].status()).toBe(200);

    // Give time for processing
    await new Promise(resolve => setTimeout(resolve, 1000));

    // Verify that the card state is consistent: the card properties still exist
    const finalCardResponse = await request.get(`/api/v2/boards/${boardId}/blocks?block_id=${cardId}`, {
      headers: {
        'Authorization': `Bearer ${user1Token}`,
        'X-Requested-With': 'XMLHttpRequest',
      }
    });
    expect(finalCardResponse.status()).toBe(200);
    const finalCardData = await finalCardResponse.json();
    const finalProperties = finalCardData[0]?.fields?.properties || {};
    console.log('Final Card Properties:', JSON.stringify(finalProperties));

    // Verify the board schema: the target column was successfully deleted
    const finalBoardResponse = await request.get(`/api/v2/boards/${boardId}`, {
      headers: {
        'Authorization': `Bearer ${user1Token}`,
        'X-Requested-With': 'XMLHttpRequest',
      }
    });
    expect(finalBoardResponse.status()).toBe(200);
    const finalBoardData = await finalBoardResponse.json();
    const finalProps = finalBoardData.cardProperties || [];
    const finalStatusProp = finalProps.find((p: any) => p.id === statusProp.id);
    const finalOptions = finalStatusProp?.options || [];
    
    console.log('Final Board Schema Options:', JSON.stringify(finalOptions));
    expect(finalOptions.some((opt: any) => opt.id === optionToMoveToId)).toBe(false);
  });

  test('CON-03: Consistencia de WebSockets - Disconnection and Catch-up', async ({ baseURL }) => {
    console.log('\n--- Running CON-03: Consistencia de WebSockets ---');
    const browser = await chromium.launch();

    // Context for User 1 (will be disconnected and reconnected)
    const context1 = await browser.newContext({ baseURL });
    const page1 = await context1.newPage();
    await loginBypass(page1, user1Token);

    // Context for User 2 (will perform changes while User 1 is offline)
    const context2 = await browser.newContext({ baseURL });
    const page2 = await context2.newPage();
    await loginBypass(page2, user2Token);

    // Go to board page
    await page1.goto(`/${boardId}`);
    await page2.goto(`/${boardId}`);

    // Wait for page load
    await expect(page1.locator('.BoardComponent')).toBeVisible();
    await expect(page2.locator('.BoardComponent')).toBeVisible();

    console.log('Disconnecting User 1 from network...');
    await context1.setOffline(true);

    const offlineText = `Card created by U2 while U1 offline ${Date.now()}`;
    console.log(`User 2 is creating a new card: "${offlineText}"`);

    // User 2 adds a card using UI
    await page2.locator('.ViewHeader .ButtonWithMenu .button-text').click();
    await expect(page2.locator('.CardDetail').first()).toBeVisible();
    await page2.locator('.CardDetail .EditableArea.title').first().click();
    await page2.locator('.CardDetail .EditableArea.title').first().fill(offlineText);
    await page2.locator('.CardDetail .EditableArea.title').first().blur();
    
    // Close card modal for User 2
    await page2.locator('.Dialog Button[title=\'Close dialog\']').click();
    await expect(page2.locator('.CardDetail').first()).not.toBeVisible();
    
    // Ensure card is visible on User 2's board
    await expect(page2.locator('.KanbanCard', { hasText: offlineText })).toBeVisible();

    // Verify card is NOT yet visible on User 1's board (since they are offline)
    console.log('Verifying that User 1 (offline) has not received the new card...');
    const cardOnU1 = page1.locator('.KanbanCard', { hasText: offlineText });
    await expect(cardOnU1).not.toBeVisible({ timeout: 2000 });

    console.log('Reconnecting User 1 network...');
    await context1.setOffline(false);

    // Wait for Websocket catch-up / reconciliation to push the updates
    console.log('Waiting for WebSocket catch-up/reconciliation...');
    
    // Verify that the new card is eventually automatically synced to User 1's UI
    await expect(cardOnU1).toBeVisible({ timeout: 15000 });
    console.log('User 1 UI automatically caught up with User 2 modifications! WebSocket reconciliation success.');

    await context1.close();
    await context2.close();
    await browser.close();
  });

  test('PER-02: Latencia de UI Optimista - Measurement', async ({ baseURL }) => {
    console.log('\n--- Running PER-02: Latencia de UI Optimista ---');
    const browser = await chromium.launch();
    const context = await browser.newContext({ baseURL });
    const page = await context.newPage();
    await loginBypass(page, user1Token);

    await page.goto(`/${boardId}`);
    await expect(page.locator('.BoardComponent')).toBeVisible();

    // We will measure the latency of card creation optimism in the UI.
    console.log('Measuring optimistic card dialog presentation latency...');
    
    const startTime = Date.now();
    await page.locator('.ViewHeader .ButtonWithMenu .button-text').click();
    
    // Wait for CardDetail to be visible
    await page.locator('.CardDetail').first().waitFor({ state: 'visible' });
    const endTime = Date.now();
    
    const latency = endTime - startTime;
    console.log(`UI Optimistic Latency (Card Detail presentation): ${latency}ms`);
    
    // Assert latency is below 200ms
    expect(latency).toBeLessThan(200);

    await context.close();
    await browser.close();
  });
});
