name: SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  sonarqube:
    name: SonarQube Cloud
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
        with:
          go-version-file: server/go.mod
          cache-dependency-path: server/go.sum

      - name: Generate Go coverage
        working-directory: server
        env:
          FOCALBOARD_UNIT_TESTING: "1"
        run: go test -tags "json1 sqlite3" -coverpkg=./... -coverprofile=coverage.out -count=1 -timeout=30m ./...

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version-file: webapp/.nvmrc
          cache: npm
          cache-dependency-path: webapp/package-lock.json

      - name: Install Webapp dependencies
        working-directory: webapp
        run: npm ci

      - name: Generate Webapp coverage
        working-directory: webapp
        run: npm test -- --coverage --runInBand

      - name: SonarQube scan
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
